### ISSUE TITLE
What is the root password for this?

### ISSUE THREAD

**Issue by azrin1972** [avafinger/bpi-m64-firmware-v2#1]

**Comment by avafinger** [comment]
It's Ubuntu. For security reasons Ubuntu does not set up **root** password, use **sudo su** instead and type **ubuntu** as password, now you are **root**.

You can always add/change root password following this: https://askubuntu.com/questions/423942/change-password-on-root-user-and-user-account

**Comment by azrin1972** [comment]
Thank you :)
