### ISSUE TITLE
Not able to access the UART for serial comm using Pin 8 & Pin 10

### ISSUE THREAD

**Issue by azrin1972** [avafinger/bpi-m64-firmware-v2#2]
Hi, How do I enable the UART of pin 8 & 10 of this board? I tried TTYS1 but there is no data coming out. I have 2 BPI-M64 and both are link using the pin 8 & 10 (crossed) - one is sending data and the other is the receiver. I'm using node-red to generate the data but I was unable to get the data through.

ls -l /dev/tttyS* shows that I have 2 options - TTYS0 and TTYS1 but I'm sure if these TTYSs are link to P8 and P10 of the GPIO

**Comment by avafinger** [comment]
You have to enable UART in the DTB.
I don't know which pin is the correct UART, beware some UART has DTR,DTS enabled.

* Save a64-2GB.dtb
* Decompile a64-2GB.dtb to a64-2GB.dts and change the UART sections to "okay":

		uart@01c28800 {
			compatible = "allwinner,sun50i-uart";
			device_type = "uart2";
			reg = <0x0 0x1c28800 0x0 0x400>;
			interrupts = <0x0 0x2 0x4>;
			clocks = <0x1e>;
			pinctrl-names = "default", "sleep";
			pinctrl-1 = <0x20>;
			uart2_port = <0x2>;
			uart2_type = <0x4>;
			/* status = "okay"; */
			status = "disabled";
			pinctrl-0 = <0xa4>;
		};

		uart@01c28c00 {
			compatible = "allwinner,sun50i-uart";
			device_type = "uart3";
			reg = <0x0 0x1c28c00 0x0 0x400>;
			interrupts = <0x0 0x3 0x4>;
			clocks = <0x21>;
			pinctrl-names = "default", "sleep";
			pinctrl-1 = <0x23>;
			uart3_port = <0x3>;
			uart3_type = <0x4>;
			/* status = "okay"; */
			status = "disabled";
			pinctrl-0 = <0xa5>;
		};

		uart@01c29000 {
			compatible = "allwinner,sun50i-uart";
			device_type = "uart4";
			reg = <0x0 0x1c29000 0x0 0x400>;
			interrupts = <0x0 0x4 0x4>;
			clocks = <0x24>;
			pinctrl-names = "default", "sleep";
			pinctrl-1 = <0x26>;
			uart4_port = <0x4>;
			uart4_type = <0x4>;
			/* status = "okay"; */
			status = "disabled";
			pinctrl-0 = <0xa6>;
		};

* Compile the changed DTS to DTB

See this on how to edit DTB:
https://github.com/avafinger/bpi-m64-firmware/issues/6

**Comment by azrin1972** [comment]
I'm new to all this, but to start with, I tried to find the dab file in my running system, but I could not find it. do I need to recompile the code?

**Comment by avafinger** [comment]
in **/media/ubuntu/boot/a64** there is the file  **a64-2GB.dtb** (device tree blob)
Yoiu need to decompile it to a file you can edit. Then you edit and modify the usb section to:
`status = "okay";`

Something like:
`dtc -I dtb -o m64.dts a64-2GB.dtb`

Edit the m64.dts, make some changes and compile again.
`dtc -I dts -O dtb -o a64-2GB.dtb m64.dts`

Update: save a copy in case something goes wrong, so you can restore it.

New image is on the way with all this enabled, i just have to finish the eMMC instructions, takes one day.

**Comment by azrin1972** [comment]
I've flashed the firmware to emmc and in my /media/ubuntu there is only emmcboot directory but it is empty

**Comment by avafinger** [comment]
sudo chmod +x *.sh
sudo ./format_emmc.sh
**sudo ./flash_emmc.sh**

**Comment by avafinger** [comment]
* click on emmcboot to be mounted!

**Comment by azrin1972** [comment]
I’m already using the emmc. I just couldn’t find the dtb file in the emmc. Maybe I should just wait for the new image

**Comment by avafinger** [comment]
what is the output:
sudo ls -la /media/ubuntu/emmcb*

**Comment by avafinger** [comment]
I have update the kernel and Image, UART is enabled.
Please try this Image: https://github.com/avafinger/bpi-m64-firmware

**Comment by azrin1972** [comment]
Ok I’ll try it today. Btw, this will delete all the content in my bpi? Or is there an upgrade procedure to this?

**Comment by avafinger** [comment]
The file system has changed to support only **ext4**, dropped vfat, so unfortunately yes, you need to format the partition again from scratch, but the files have been reduced to a minimum and does not take much time as usual in IMG format,  you can save your .bash_history and replay all the commands within your new Image and/or data, and then restore to your position.

the .bash_history contains all commands you have typed so far in Shell.
the file is : ls -la .bash_history, just edit to see the contents.

**Comment by azrin1972** [comment]
Ok thank you. Will update the outcome once I’ve completed the installation and test.

**Comment by azrin1972** [comment]
A question: if I want to use the GPIO pins, does the firmware today supports it or do I need to recompile the DTB files?

**Comment by avafinger** [comment]
Yes, there is support for GPIO pins but you have to enable it in m64.dtb_1080p (if using 1080p) or m64.dtb_720p (if using 720p)

Make a copy in case you need it later.

Do:
```
cd /media/ubuntu/boot/a64
sudo dtc -I dtb -o m64.dts m64.dtb_1080p

```

enable gpio section, just change:
gpio_used = <0x0>;  to gpio_used = <**0x1**>;

`sudo leafpad m64.dtb_1080p`

and recompile
```
sudo dtc -I dts -O dtb -o m64.dtb_1080p m64.dts
sync

```

**sudo reboot** after that

**Comment by azrin1972** [comment]
Tested using pin 8 and 10 (/dev/ttyS2) working great!!
Thanks for the update.
Offcially will close this issue
